### ISSUE TITLE
Update Remotery to fix Linux build

### ISSUE THREAD

**Issue by makuto** [dougbinks/enkiTSExamples#2]
Currently, the Linux build fails with the following errors:
``` c
/home/macoy/Repositories/enkiTSExamples/Remotery/lib/Remotery.c:5212:84: error: unknown type name ‘CONTEXT’
 5212 | static rmtBool ThreadProfilers_ThreadInCallback(ThreadProfilers* thread_profilers, CONTEXT* context)
      |                                                                                    ^~~~~~~
/home/macoy/Repositories/enkiTSExamples/Remotery/lib/Remotery.c:5212:84: error: unknown type name ‘CONTEXT’
 5212 | static rmtBool ThreadProfilers_ThreadInCallback(ThreadProfilers* thread_profilers, CONTEXT* context)
      |                                                                                    ^~~~~~~
```
The fix is to replace `CONTEXT` with `rmtCpuContext`. The master branch of Remotery doesn't have this problem.
I didn't want to make a PR because I was mainly interested in testing the Microprofile part, so testing the Remotery part with the newest branch wasn't something I wanted to do.

**Comment by dougbinks** [comment]
I'll take a look at updating the Remotery submodule, thanks for the report.

**Comment by dougbinks** [comment]
I've updated Remotery but experienced problems, see this PR:
https://github.com/Celtoys/Remotery/pull/180

**Comment by dougbinks** [comment]
The Remotery issues have been resolved, and I've updated the submodule with those changes.
